backend:
  name: git-gateway
  branch: main

locale: 'ko'
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "food"
    label: "음식"
    folder: "src/pages/Blog/Food"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
      - { label: "레이아웃", name: "layout", widget: "hidden", default: "../../../layouts/PostLayout.astro" }

  - name: "performance"
    label: "공연"
    folder: "src/pages/Blog/Performance"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
      - { label: "레이아웃", name: "layout", widget: "hidden", default: "../../../layouts/PostLayout.astro" }

  - name: "diary"
    label: "일기"
    folder: "src/pages/Blog/Diary"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
      - { label: "레이아웃", name: "layout", widget: "hidden", default: "../../../layouts/PostLayout.astro" }